"""Generate docs/configuration.md from the settings table and its explanations.

Why generated and not written: a hand-written configuration page is a COPY of
what the tool knows, and copies drift. v0.5.10 added `sync_removals`, so any
page written the day before was already wrong about a setting that MOVES
FILES. Generating it means the page cannot describe a ccs that never shipped.

    python scripts/gen-config-docs.py            # write the page
    python scripts/gen-config-docs.py --check    # exit 1 if it is out of date

The --check mode is what tests/test_config_docs_current.py runs, so a setting
added without regenerating fails the suite rather than shipping a stale page.
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO))

from dazzle_claude_config import userconfig  # noqa: E402

PAGE = REPO / "docs" / "configuration.md"

HEADER = """<!-- GENERATED by scripts/gen-config-docs.py -- do not edit by hand.
     The words come from dazzle_claude_config/settings-explanations.json;
     the defaults and environment variables from dazzle_claude_config/userconfig.py.
     Edit those, then re-run the script. -->

# Configuration

ccs reads its preferences from `~/claude/ccs-config.json`. Every setting also has an environment variable, which wins for a single shell, and most have a command-line flag, which wins for a single run:

    explicit flag  >  environment variable  >  config file  >  built-in default

The file is optional. A machine with no config at all behaves safely -- ccs prompts rather than guessing, and never spends money without being asked.

## Keeping the file current

A config file freezes at the settings of whatever version wrote it. `ccs setup update` adds the ones this version knows, at their documented defaults, and changes nothing you have set:

    ccs setup update --dry-run     # show exactly what would be added
    ccs setup update               # add them
    ccs setup update --explain sync_removals    # what one setting means, offline

You do not need this page to answer a question about one setting -- `--explain <name>` prints the same words in your terminal, with no network and no config file. This page exists for reading them all at once.

## Every setting
"""

FOOTER = """
---

*This page is generated. To correct the wording of a setting, edit `dazzle_claude_config/settings-explanations.json` and run `python scripts/gen-config-docs.py`. To change a default or add a setting, edit `dazzle_claude_config/userconfig.py` as well.*
"""


def render() -> str:
    keys = userconfig.KEYS
    out = [HEADER]

    out.append("\n| Setting | Default | Environment variable |")
    out.append("|---|---|---|")
    for name, k in keys.items():
        # The anchor is the heading text itself. It used to be
        # `name.replace('_', '-')`, on the assumption that GitHub turns
        # underscores into hyphens the way it does spaces. It does not --
        # underscores survive slugging -- so every multi-word setting linked
        # to a section that does not exist: 8 of the 11 were dead, and the 3
        # that worked were the single-word names, by coincidence.
        #
        # Every setting name is already lowercase with no punctuation, so the
        # slug is the name unchanged. Deriving it from `name` rather than
        # transforming it keeps the link and the `### {name}` heading below
        # correct by construction instead of by agreement.
        out.append(f"| [`{name}`](#{name}) "
                   f"| `{json.dumps(k.default)}` | `{k.env}` |")
    out.append("")

    for name, k in keys.items():
        out.append(f"\n### {name}\n")
        bits = [f"**Default:** `{json.dumps(k.default)}`",
                f"**Environment:** `{k.env}`"]
        if k.choices:
            bits.append("**One of:** "
                        + ", ".join(f"`{c}`" for c in sorted(k.choices)))
        out.append(" &middot; ".join(bits) + "\n")
        # One line per paragraph, unwrapped: Markdown reflows, and hard breaks
        # inside a paragraph mis-render in lists and make the source painful.
        out.append(k.explain)

    out.append(FOOTER)
    return "\n".join(out).rstrip() + "\n"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true",
                    help="exit 1 if the page on disk is out of date")
    args = ap.parse_args()

    missing, orphan = userconfig.explanation_gaps(
        userconfig.KEYS, userconfig.EXPLANATIONS)
    if missing or orphan:
        for n in sorted(missing):
            print(f"error: setting '{n}' has no explanation", file=sys.stderr)
        for n in sorted(orphan):
            print(f"error: explanation '{n}' names no setting", file=sys.stderr)
        return 2

    fresh = render()
    if args.check:
        current = PAGE.read_text(encoding="utf-8") if PAGE.exists() else ""
        if current != fresh:
            print(f"{PAGE.relative_to(REPO)} is out of date -- run "
                  f"python scripts/gen-config-docs.py", file=sys.stderr)
            return 1
        print(f"{PAGE.relative_to(REPO)} is current ({len(userconfig.KEYS)} "
              f"settings)")
        return 0

    PAGE.parent.mkdir(parents=True, exist_ok=True)
    PAGE.write_text(fresh, encoding="utf-8")
    print(f"wrote {PAGE.relative_to(REPO)} ({len(userconfig.KEYS)} settings)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
